# Generated by Django 6.0.7 on 2026-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnasayfaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('hedef_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'anasayfa_linkler',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('resim', models.CharField(max_length=255)),
                ('view', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'duyurular',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('resim', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'haberler',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sicil_no', models.CharField(max_length=50)),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('sifre', models.CharField(max_length=255)),
                ('dogum_tarihi', models.DateField()),
                ('foto_url', models.CharField(max_length=255)),
                ('remember_token_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('remember_token_expires', models.DateTimeField(blank=True, null=True)),
                ('tc_no', models.CharField(blank=True, max_length=11, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'personeller',
                'ordering': ['ad', 'soyad'],
            },
        ),
    ]
