# Generated by Django 6.0.7 on 2026-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0002_unmanaged_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnasayfaDuyurular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('resim', models.CharField(max_length=255)),
                ('view', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Anasayfa duyuru',
                'verbose_name_plural': 'Anasayfa duyurular',
                'db_table': 'anasayfa_duyurular',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnasayfaLinkler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('hedef_url', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Anasayfa link',
                'verbose_name_plural': 'Anasayfa linkler',
                'db_table': 'anasayfa_linkler',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnketCevaplari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cevap_metni', models.TextField(blank=True, null=True)),
                ('olusturma_tarihi', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Anket cevaplari',
                'db_table': 'anket_cevaplari',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnketKatilimlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anket_id', models.IntegerField()),
                ('personel_id', models.IntegerField()),
                ('tamamlanma_tarihi', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Anket katilimlari',
                'db_table': 'anket_katilimlari',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anketler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('resim_url', models.CharField(blank=True, max_length=500, null=True)),
                ('baslangic_tarihi', models.DateField(blank=True, null=True)),
                ('bitis_tarihi', models.DateField(blank=True, null=True)),
                ('katilim_sayisi', models.IntegerField(blank=True, null=True)),
                ('hedef_katilim', models.IntegerField(blank=True, null=True)),
                ('favori', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Anketler',
                'db_table': 'anketler',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnketlerKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('ad', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Anket kategorileri',
                'db_table': 'anketler_kategori',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnketSecenekleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secenek_metni', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Anket secenekleri',
                'db_table': 'anket_secenekleri',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnketSorulari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_metni', models.TextField()),
                ('soru_tipi', models.CharField(max_length=255)),
                ('sira', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Anket sorulari',
                'db_table': 'anket_sorulari',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Duyurular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('resim', models.CharField(max_length=255)),
                ('view', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Duyurular',
                'db_table': 'duyurular',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DuyurularKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('ad', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Duyuru kategorileri',
                'db_table': 'duyurular_kategori',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etkinlikler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('tarih', models.DateField()),
                ('bitis_tarihi', models.DateField(blank=True, null=True)),
                ('view', models.IntegerField(blank=True, null=True)),
                ('resim', models.CharField(blank=True, max_length=255, null=True)),
                ('durum', models.CharField(default='aktif', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Etkinlikler',
                'db_table': 'etkinlikler',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtkinliklerDurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('ad', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Etkinlik durumlari',
                'db_table': 'etkinlikler_durum',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtkinliklerDuyurular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayfa_tipi', models.CharField(max_length=50)),
                ('baslik', models.CharField(max_length=255)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('resim_url', models.CharField(blank=True, max_length=255, null=True)),
                ('tarih', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Etkinlik duyurulari',
                'db_table': 'etkinlikler_duyurular',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HaberGaleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim_url', models.CharField(max_length=255)),
                ('sira', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Haber galeri',
                'db_table': 'haber_galeri',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Haberler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('resim', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Haberler',
                'db_table': 'haberler',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IcerikIzlemeleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablo', models.CharField(max_length=64)),
                ('kayit_id', models.IntegerField()),
                ('izleyici', models.CharField(max_length=96)),
                ('olusturma_tarihi', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Icerik izlemeleri',
                'db_table': 'icerik_izlemeleri',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kaynaklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('ikon', models.CharField(blank=True, max_length=50, null=True)),
                ('dosya_yolu', models.CharField(max_length=255)),
                ('resmi_sayfa', models.CharField(blank=True, max_length=500, null=True)),
                ('boyut', models.CharField(max_length=50)),
                ('tarih', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Kaynaklar',
                'db_table': 'kaynaklar',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KaynaklarAltKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('ad', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Kaynak alt kategorileri',
                'db_table': 'kaynaklar_alt_kategori',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KaynaklarKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('ad', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Kaynak kategorileri',
                'db_table': 'kaynaklar_kategori',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OturumKayitlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giris_zamani', models.DateTimeField()),
                ('cikis_zamani', models.DateTimeField(blank=True, null=True)),
                ('ip_adresi', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('kapanis_tipi', models.CharField(blank=True, max_length=20, null=True)),
                ('son_aktivite', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Oturum kayitlari',
                'db_table': 'oturum_kayitlari',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sicil_no', models.CharField(max_length=50, unique=True)),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('sifre', models.CharField(max_length=255)),
                ('dogum_tarihi', models.DateField()),
                ('foto_url', models.CharField(max_length=255)),
                ('remember_token_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('remember_token_expires', models.DateTimeField(blank=True, null=True)),
                ('tc_no', models.CharField(blank=True, max_length=11, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Personeller',
                'db_table': 'personeller',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteIkonlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anahtar', models.CharField(max_length=100, unique=True)),
                ('ad', models.CharField(max_length=150)),
                ('kategori', models.CharField(max_length=50)),
                ('ikon_sinifi', models.CharField(max_length=150)),
                ('renk', models.CharField(blank=True, max_length=30, null=True)),
                ('sira', models.IntegerField()),
                ('aktif', models.SmallIntegerField()),
                ('olusturma_tarihi', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Site ikonlari',
                'db_table': 'site_ikonlari',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SizdenGelenler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('ozet', models.TextField()),
                ('tarih', models.DateField()),
                ('goruntulenme', models.IntegerField(blank=True, null=True)),
                ('gorsel_yolu', models.CharField(blank=True, max_length=255, null=True)),
                ('olusturma_tarihi', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Sizden gelenler',
                'db_table': 'sizden_gelenler',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SizdengelenlerKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('ad', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Sizden gelenler kategorileri',
                'db_table': 'sizdengelenler_kategori',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VefatBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vefat_eden_adi', models.CharField(max_length=255)),
                ('iliski_pozisyon', models.TextField()),
                ('vefat_tarihi', models.DateField()),
                ('vefat_tarihi_metin', models.CharField(max_length=50)),
                ('cenaze_mesaji', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Vefat bilgileri',
                'db_table': 'vefat_bilgileri',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Videolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=50, unique=True)),
                ('baslik', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('sure', models.CharField(max_length=20)),
                ('vitrin', models.SmallIntegerField()),
                ('vitrin_baslik', models.CharField(blank=True, max_length=255, null=True)),
                ('vitrin_aciklama', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Videolar',
                'db_table': 'videolar',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideolarKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('ad', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Video kategorileri',
                'db_table': 'videolar_kategori',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YardimciLinkler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('hedef_url', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Yardimci linkler',
                'db_table': 'yardimci_linkler',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YardimciLinklerKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('ad', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Yardimci link kategorileri',
                'db_table': 'yardimci_linkler_kategori',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Yoneticiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=50, unique=True)),
                ('sifre', models.CharField(max_length=255)),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('yetki', models.CharField(max_length=255)),
                ('aktif', models.SmallIntegerField()),
                ('olusturma_tarihi', models.DateTimeField()),
                ('foto_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Yoneticiler',
                'db_table': 'yoneticiler',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YoneticiOturumKayitlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giris_zamani', models.DateTimeField()),
                ('cikis_zamani', models.DateTimeField(blank=True, null=True)),
                ('ip_adresi', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('kapanis_tipi', models.CharField(blank=True, max_length=20, null=True)),
                ('son_aktivite', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Yonetici oturum kayitlari',
                'db_table': 'yonetici_oturum_kayitlari',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
